spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3307/userDB
    username: userDB
    password: userpassword
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
      
keycloak:
  realm: safe-transport
  domain: localhost:9081
#  adminClientId: admin-cli
#  adminClientSecret: Sr6CXPYmJ9rSdiGAJftPcey2ad85RjI7
#  client: authenticationClientId
#  urls:
#    auth: http://${keycloak.domain}

jwt:
  auth:
    converter:
      resource-id: authClientID

server:
  port: 8090