spring:
  application:
    name: organization-service
  datasource:
    url: jdbc:mysql://localhost:3306/muntasir
    username: muntasir
    password: muntasir

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 8092